#!/bin/sh

ROOT=/home/nephrite/rss
MAXF=100

cd $ROOT/feeds
echo See progress with tail -f $ROOT/wget-log
wget --user-agent='Mozilla' -t 3 -T 20 -N -x -o $ROOT/wget-log -i $ROOT/list 
cd $ROOT

rm -f $ROOT/items/new
if [ -e last_run ]; then
	find $ROOT/feeds -type f -newer last_run | xargs -L $MAXF $ROOT/parser
else
	find $ROOT/feeds -type f | xargs -L $MAXF $ROOT/parser
fi

touch last_run

$ROOT/sorter news
