#!/bin/sh

ROOT=/home/nephrite/rss
BIN=$ROOT/bin

cd $ROOT/config

FROM=''
TO=''
while getopts f:t: OPT; do
	case $OPT in
		f) FROM="-f $OPTARG"
		;;
		t) TO="-t $OPTARG"
		;;
	esac
done

export PERL5LIB=$ROOT
for feed in *
do
	if [ $feed != 'config' ]; then
		$BIN/aggregator $feed
		$BIN/rss2html $FROM $TO $feed
	fi
done

